"""CLI-only reporting: brands, commercials, songs, timeline, summary."""

from radio_classifier.reports.artist_plays import (
    render_artist_plays_html,
    write_artist_plays,
)
from radio_classifier.reports.dashboard import render_dashboard_html, write_dashboard
from radio_classifier.reports.format import (
    format_artists,
    format_brands,
    format_commercials,
    format_discoveries,
    format_runs,
    format_songs,
    format_songs_added,
    format_songs_timeline,
    format_summary,
    format_timeline,
)
from radio_classifier.reports.queries import (
    PROMO_MAX_SPIN_SECONDS,
    ArtistPlay,
    ArtistPlaylog,
    artists_top,
    brands_top,
    commercials_by_brand,
    commercials_top,
    parse_since,
    runs_summary,
    songs_added,
    songs_timeline,
    songs_top,
    summary,
    timeline,
    top_artist_playlogs,
)

__all__ = [
    "PROMO_MAX_SPIN_SECONDS",
    "ArtistPlay",
    "ArtistPlaylog",
    "artists_top",
    "brands_top",
    "commercials_by_brand",
    "commercials_top",
    "format_artists",
    "format_brands",
    "format_commercials",
    "format_discoveries",
    "format_runs",
    "format_songs",
    "format_songs_added",
    "format_songs_timeline",
    "format_summary",
    "format_timeline",
    "parse_since",
    "render_artist_plays_html",
    "render_dashboard_html",
    "runs_summary",
    "songs_added",
    "songs_timeline",
    "songs_top",
    "summary",
    "timeline",
    "top_artist_playlogs",
    "write_artist_plays",
    "write_dashboard",
]
